/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: string | null;
  accountId: string;
  createdAt: string;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: string | null;
  scope: string | null;
  updatedAt: string;
  userId: string;
}

export interface Charge {
  amount_pence: number;
  charge_date: string;
  created_at: Generated<string>;
  created_by: string;
  deleted_at: string | null;
  deleted_by: string | null;
  deleted_reason: string | null;
  description: string;
  id: string;
  member_id: string;
  paid_at: string | null;
  payment_confirmed_at: string | null;
  source: Generated<string>;
  stripe_payment_intent_id: string | null;
  type: Generated<string>;
}

export interface ChargeDependent {
  charge_id: string;
  dependent_id: string;
}

export interface ContactSubmission {
  created_at: Generated<string>;
  email: string;
  id: string;
  message: string;
  name: string;
  page: string;
}

export interface Dependent {
  alt_contact_name: string | null;
  alt_contact_phone: string | null;
  alt_contact_whatsapp_consent: number | null;
  created_at: Generated<string>;
  data_protection_consent: number | null;
  disability_type: string | null;
  dob: string;
  emergency_medical_consent: number | null;
  gp_phone: string | null;
  gp_surgery: string | null;
  has_disability: number | null;
  id: string;
  medical_fitness_declaration: number | null;
  medical_info: string | null;
  member_id: string;
  name: string;
  photo_consent: number | null;
  play_cricket_id: string | null;
  played_before: number | null;
  previous_cricket: string | null;
  school_year: string | null;
  sex: string;
  whatsapp_consent: number | null;
}

export interface EventSubscriber {
  email: string;
  id: string;
  meta: string;
}

export interface GameScore {
  best_streak: number;
  catches: number;
  game: Generated<string>;
  id: string;
  level: number;
  score: number;
  updated_at: string;
  user_id: string;
}

export interface GameSponsorship {
  amount_pence: number;
  approved: Generated<number>;
  created_at: Generated<string>;
  display_name: string | null;
  game_id: string;
  id: string | null;
  notes: string | null;
  paid_at: string | null;
  sponsor_email: string;
  sponsor_logo_url: string | null;
  sponsor_message: string | null;
  sponsor_name: string;
  sponsor_website: string | null;
  stripe_payment_intent_id: string | null;
}

export interface JuniorTeam {
  age_group: string;
  created_at: Generated<string>;
  id: string | null;
  name: string;
  sex: string;
}

export interface JuniorTeamManager {
  junior_team_id: string;
  user_id: string;
}

export interface MatchPerformanceBatting {
  balls: Generated<number>;
  competition_type: Generated<string>;
  created_at: Generated<string>;
  fours: Generated<number>;
  how_out: Generated<string>;
  id: string | null;
  match_date: string;
  match_id: string;
  not_out: Generated<number>;
  player_id: string;
  player_name: string;
  runs: Generated<number>;
  season: number;
  sixes: Generated<number>;
  team_id: string;
}

export interface MatchPerformanceBowling {
  competition_type: Generated<string>;
  created_at: Generated<string>;
  id: string | null;
  maidens: Generated<number>;
  match_date: string;
  match_id: string;
  no_balls: Generated<number>;
  overs: Generated<string>;
  player_id: string;
  player_name: string;
  runs: Generated<number>;
  season: number;
  team_id: string;
  wickets: Generated<number>;
  wides: Generated<number>;
}

export interface Member {
  address: string;
  contentful_entry_id: string | null;
  dob: string;
  email: string;
  emergency_contact_name: string;
  emergency_contact_telephone: string;
  id: string;
  name: string;
  play_cricket_id: string | null;
  postcode: string;
  stripe_customer_id: string | null;
  telephone: string;
  title: string;
}

export interface Membership {
  created_at: Generated<string>;
  dependent_id: string | null;
  id: string;
  member_id: string;
  paid_until: string;
  type: string | null;
}

export interface Passkey {
  backedUp: number;
  counter: number;
  createdAt: string | null;
  credentialID: string;
  deviceType: string;
  id: string;
  name: string | null;
  publicKey: string;
  transports: string | null;
  userId: string;
}

export interface PlayCricketMatchCache {
  data: string;
  fetched_at: string;
  match_date: string;
  match_id: string | null;
}

export interface PlayCricketSyncLog {
  completed_at: string | null;
  errors: string | null;
  id: string | null;
  matches_processed: Generated<number>;
  season: number;
  started_at: string;
}

export interface PlayCricketTeam {
  created_at: Generated<string>;
  id: string | null;
  is_junior: Generated<number>;
  last_updated: string | null;
  name: string;
  site_id: string;
}

export interface PlayerSponsorship {
  amount_pence: number;
  approved: Generated<number>;
  contentful_entry_id: string;
  created_at: Generated<string>;
  display_name: string | null;
  id: string | null;
  notes: string | null;
  paid_at: string | null;
  player_name: string;
  season: number;
  sponsor_email: string;
  sponsor_logo_url: string | null;
  sponsor_message: string | null;
  sponsor_name: string;
  sponsor_website: string | null;
  stripe_payment_intent_id: string | null;
}

export interface Session {
  createdAt: string;
  expiresAt: string;
  id: string;
  impersonatedBy: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: string;
  userAgent: string | null;
  userId: string;
}

export interface TwoFactor {
  backupCodes: string;
  id: string;
  secret: string;
  userId: string;
}

export interface User {
  banExpires: string | null;
  banned: number | null;
  banReason: string | null;
  createdAt: string;
  email: string;
  emailVerified: number;
  id: string;
  image: string | null;
  name: string;
  role: string | null;
  twoFactorEnabled: number | null;
  updatedAt: string;
}

export interface Verification {
  createdAt: string | null;
  expiresAt: string;
  id: string;
  identifier: string;
  updatedAt: string | null;
  value: string;
}

export interface DB {
  account: Account;
  charge: Charge;
  charge_dependent: ChargeDependent;
  contact_submission: ContactSubmission;
  dependent: Dependent;
  event_subscriber: EventSubscriber;
  game_score: GameScore;
  game_sponsorship: GameSponsorship;
  junior_team: JuniorTeam;
  junior_team_manager: JuniorTeamManager;
  match_performance_batting: MatchPerformanceBatting;
  match_performance_bowling: MatchPerformanceBowling;
  member: Member;
  membership: Membership;
  passkey: Passkey;
  play_cricket_match_cache: PlayCricketMatchCache;
  play_cricket_sync_log: PlayCricketSyncLog;
  play_cricket_team: PlayCricketTeam;
  player_sponsorship: PlayerSponsorship;
  session: Session;
  twoFactor: TwoFactor;
  user: User;
  verification: Verification;
}
