export { isTypeAssetLink } from "./TypeAssetLink";
export type { TypeAssetLink, TypeAssetLinkFields, TypeAssetLinkSkeleton, TypeAssetLinkWithAllLocalesAndWithoutLinkResolutionResponse, TypeAssetLinkWithAllLocalesAndWithoutUnresolvableLinksResponse, TypeAssetLinkWithAllLocalesResponse, TypeAssetLinkWithoutLinkResolutionResponse, TypeAssetLinkWithoutUnresolvableLinksResponse } from "./TypeAssetLink";
export { isTypeEmailCollector } from "./TypeEmailCollector";
export type { TypeEmailCollector, TypeEmailCollectorFields, TypeEmailCollectorSkeleton, TypeEmailCollectorWithAllLocalesAndWithoutLinkResolutionResponse, TypeEmailCollectorWithAllLocalesAndWithoutUnresolvableLinksResponse, TypeEmailCollectorWithAllLocalesResponse, TypeEmailCollectorWithoutLinkResolutionResponse, TypeEmailCollectorWithoutUnresolvableLinksResponse } from "./TypeEmailCollector";
export { isTypeEvent } from "./TypeEvent";
export type { TypeEvent, TypeEventFields, TypeEventSkeleton, TypeEventWithAllLocalesAndWithoutLinkResolutionResponse, TypeEventWithAllLocalesAndWithoutUnresolvableLinksResponse, TypeEventWithAllLocalesResponse, TypeEventWithoutLinkResolutionResponse, TypeEventWithoutUnresolvableLinksResponse } from "./TypeEvent";
export { isTypeFixtureList } from "./TypeFixtureList";
export type { TypeFixtureList, TypeFixtureListFields, TypeFixtureListSkeleton, TypeFixtureListWithAllLocalesAndWithoutLinkResolutionResponse, TypeFixtureListWithAllLocalesAndWithoutUnresolvableLinksResponse, TypeFixtureListWithAllLocalesResponse, TypeFixtureListWithoutLinkResolutionResponse, TypeFixtureListWithoutUnresolvableLinksResponse } from "./TypeFixtureList";
export { isTypeGame } from "./TypeGame";
export type { TypeGame, TypeGameFields, TypeGameSkeleton, TypeGameWithAllLocalesAndWithoutLinkResolutionResponse, TypeGameWithAllLocalesAndWithoutUnresolvableLinksResponse, TypeGameWithAllLocalesResponse, TypeGameWithoutLinkResolutionResponse, TypeGameWithoutUnresolvableLinksResponse } from "./TypeGame";
export { isTypeGameDetail } from "./TypeGameDetail";
export type { TypeGameDetail, TypeGameDetailFields, TypeGameDetailSkeleton, TypeGameDetailWithAllLocalesAndWithoutLinkResolutionResponse, TypeGameDetailWithAllLocalesAndWithoutUnresolvableLinksResponse, TypeGameDetailWithAllLocalesResponse, TypeGameDetailWithoutLinkResolutionResponse, TypeGameDetailWithoutUnresolvableLinksResponse } from "./TypeGameDetail";
export { isTypeLeague } from "./TypeLeague";
export type { TypeLeague, TypeLeagueFields, TypeLeagueSkeleton, TypeLeagueWithAllLocalesAndWithoutLinkResolutionResponse, TypeLeagueWithAllLocalesAndWithoutUnresolvableLinksResponse, TypeLeagueWithAllLocalesResponse, TypeLeagueWithoutLinkResolutionResponse, TypeLeagueWithoutUnresolvableLinksResponse } from "./TypeLeague";
export { isTypeLocation } from "./TypeLocation";
export type { TypeLocation, TypeLocationFields, TypeLocationSkeleton, TypeLocationWithAllLocalesAndWithoutLinkResolutionResponse, TypeLocationWithAllLocalesAndWithoutUnresolvableLinksResponse, TypeLocationWithAllLocalesResponse, TypeLocationWithoutLinkResolutionResponse, TypeLocationWithoutUnresolvableLinksResponse } from "./TypeLocation";
export { isTypeNews } from "./TypeNews";
export type { TypeNews, TypeNewsFields, TypeNewsSkeleton, TypeNewsWithAllLocalesAndWithoutLinkResolutionResponse, TypeNewsWithAllLocalesAndWithoutUnresolvableLinksResponse, TypeNewsWithAllLocalesResponse, TypeNewsWithoutLinkResolutionResponse, TypeNewsWithoutUnresolvableLinksResponse } from "./TypeNews";
export { isTypePage } from "./TypePage";
export type { TypePage, TypePageFields, TypePageSkeleton, TypePageWithAllLocalesAndWithoutLinkResolutionResponse, TypePageWithAllLocalesAndWithoutUnresolvableLinksResponse, TypePageWithAllLocalesResponse, TypePageWithoutLinkResolutionResponse, TypePageWithoutUnresolvableLinksResponse } from "./TypePage";
export { isTypeSiteData } from "./TypeSiteData";
export type { TypeSiteData, TypeSiteDataFields, TypeSiteDataSkeleton, TypeSiteDataWithAllLocalesAndWithoutLinkResolutionResponse, TypeSiteDataWithAllLocalesAndWithoutUnresolvableLinksResponse, TypeSiteDataWithAllLocalesResponse, TypeSiteDataWithoutLinkResolutionResponse, TypeSiteDataWithoutUnresolvableLinksResponse } from "./TypeSiteData";
export { isTypeSponsor } from "./TypeSponsor";
export type { TypeSponsor, TypeSponsorFields, TypeSponsorSkeleton, TypeSponsorWithAllLocalesAndWithoutLinkResolutionResponse, TypeSponsorWithAllLocalesAndWithoutUnresolvableLinksResponse, TypeSponsorWithAllLocalesResponse, TypeSponsorWithoutLinkResolutionResponse, TypeSponsorWithoutUnresolvableLinksResponse } from "./TypeSponsor";
export { isTypeTeam } from "./TypeTeam";
export type { TypeTeam, TypeTeamFields, TypeTeamSkeleton, TypeTeamWithAllLocalesAndWithoutLinkResolutionResponse, TypeTeamWithAllLocalesAndWithoutUnresolvableLinksResponse, TypeTeamWithAllLocalesResponse, TypeTeamWithoutLinkResolutionResponse, TypeTeamWithoutUnresolvableLinksResponse } from "./TypeTeam";
export { isTypeTrustee } from "./TypeTrustee";
export type { TypeTrustee, TypeTrusteeFields, TypeTrusteeSkeleton, TypeTrusteeWithAllLocalesAndWithoutLinkResolutionResponse, TypeTrusteeWithAllLocalesAndWithoutUnresolvableLinksResponse, TypeTrusteeWithAllLocalesResponse, TypeTrusteeWithoutLinkResolutionResponse, TypeTrusteeWithoutUnresolvableLinksResponse } from "./TypeTrustee";
